name: Update GitHub Contribution Radar

on:
  schedule:
    - cron: '0 0 * * 1'  # every Monday at midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Generate Radar Chart using wakatime
      uses: anmol098/waka-readme-stats@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        SHOW_DAYS_OF_WEEK: "True"
        SHOW_LANGUAGE_PER_REPO: "False"
        SHOW_TIMEZONE: "True"
        SHOW_EDITORS: "False"
        SHOW_LINES_OF_CODE: "False"
        SHOW_SHORT_INFO: "False"
        SHOW_LOC_CHART: "False"
        SHOW_PROJECTS: "False"
        SHOW_LANGUAGE: "False"
        SHOW_OS: "False"
        SHOW_COMMIT: "True"
