name: Update GitHub Contribution Radar

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at midnight
  workflow_dispatch:     # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Generate WakaTime Stats
      uses: anmol098/waka-readme-stats@master
      with:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        SHOW_DAYS_OF_WEEK: "True"
        SHOW_LANGUAGE_PER_REPO: "True"
        SHOW_TIMEZONE: "True"
        SHOW_EDITORS: "True"
        SHOW_LINES_OF_CODE: "True"
        SHOW_SHORT_INFO: "True"
        SHOW_LOC_CHART: "True"
        SHOW_PROJECTS: "True"
        SHOW_LANGUAGE: "True"
        SHOW_OS: "True"
        SHOW_COMMIT: "True"
